FROM ruby_base AS rails_base

RUN gem install rails -v "6.1.7"

RUN rails new myapp -d sqlite3 --api

WORKDIR /myapp

RUN rake db:create

# run with he built-in puma webserver
CMD ["rails", "server", "-b", "0.0.0.0", "-p", "8080"]
