FROM rails_base

RUN gem install puma

ADD application_controller.rb app/controllers/
ADD routes.rb config/
ADD puma.rb config/

ADD Gemfile .
RUN bundle install

EXPOSE 8080

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
