FROM rails_base

RUN gem install unicorn

ADD application_controller.rb app/controllers/
ADD routes.rb config/
ADD unicorn.rb config/

ADD Gemfile .
RUN bundle install

RUN mkdir -p shared/pids shared/log

EXPOSE 8080

CMD ["unicorn", "-c", "config/unicorn.rb", "-E", "production"]
