FROM ruby_base AS rails_base

RUN gem install rails -v "~> 6.1.6.1"

RUN gem install unicorn

RUN rails new app -d sqlite3 --api

WORKDIR /app

RUN rake db:create

CMD ["rails", "server", "-b", "0.0.0.0", "-p", "8080"]
